services:
  pingvin-share:
    image: stonith404/pingvin-share:latest
    container_name: pingvin-share
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - TRUST_PROXY=true
    volumes:
      - ${DATA_DIR}/pingvin-share/data:/opt/app/backend/data
      - ${DATA_DIR}/pingvin-share/data/images:/opt/app/frontend/public/img
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.pingvin.rule=Host(`pingvin.${BASE_DOMAIN}`)
      - traefik.http.routers.pingvin.entrypoints=websecure
      - traefik.http.routers.pingvin.tls.certresolver=le
      - traefik.http.routers.pingvin.middlewares=security-headers@docker
      - traefik.http.services.pingvin.loadbalancer.server.port=3000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

